output "private_subnets_ids" {
  value = "${module.vpc.private_subnets}"
}

output "public_subnets_ids" {
  value = "${module.vpc.public_subnets}"
}

output "vpc-id" {
  value = "${module.vpc.vpc_id}"
}

output "custom_worker_iam_role_arn" {
  value = module.iam_assumable_role.custom_worker_iam_role_arn
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.my-cluster.cluster_endpoint
}

output "workers_asg_arns" {
  description = "Endpoint for EKS control plane."
  value       = module.my-cluster.workers_asg_arns
}

output "cluster_id" {
  description = "Name of EKS cluster."
  value       = module.my-cluster.cluster_id
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.my-cluster.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.my-cluster.kubeconfig
}

output "kubernetes_namespace_dns" {
  value = kubernetes_namespace.dns.metadata[0].name
}

output "kubernetes_namespace_ingress" {
  value = kubernetes_namespace.ingress.metadata[0].name
}
